export const metadata = {
	title: 'Next App',
	description: 'Generated by assistant'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				{children}
			</body>
			</html>
	)
}
